# Generated by Django 4.1.1 on 2022-11-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="email",
            field=models.CharField(
                choices=[("W", "Weekly"), ("M", "Monthly")], max_length=2
            ),
        ),
    ]
