# Generated by Django 4.1.1 on 2022-11-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0002_alter_subscribe_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribe",
            name="option",
            field=models.CharField(
                choices=[("W", "Weekly"), ("M", "Monthly")], default="W", max_length=2
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscribe",
            name="email",
            field=models.EmailField(max_length=200),
        ),
    ]
