# Generated by Django 4.1.1 on 2022-11-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0003_subscribe_option_alter_subscribe_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="option",
            field=models.CharField(
                choices=[("W", "Weekly"), ("M", "Monthly")], default="W", max_length=2
            ),
        ),
    ]
