# Generated by Django 4.1.1 on 2022-11-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0004_alter_subscribe_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="option",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                default="W",
                max_length=10,
            ),
        ),
    ]
