# Generated by Django 4.1.1 on 2022-10-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_jobpost_date_jobpost_description_jobpost_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
