# Generated by Django 4.1.2 on 2022-11-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_slug_jobpost_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobpost",
            old_name="url",
            new_name="slug",
        ),
    ]
