# Generated by Django 4.1.1 on 2022-11-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_rename_slug_jobpost_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="expire",
            field=models.DateField(null=True),
        ),
    ]
