# Generated by Django 4.1.1 on 2022-11-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_skills_jobpost_skills"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skills",
            new_name="Skill",
        ),
    ]
