# Generated by Django 4.1.1 on 2022-11-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_apply_jobpost_apply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="apply",
        ),
        migrations.DeleteModel(
            name="Apply",
        ),
    ]
