# Generated by Django 4.1.1 on 2022-11-18 14:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applybank", "0002_remove_apply_job_id"),
        ("app", "0016_remove_jobpost_apply_delete_apply"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="apply",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="applybank.apply",
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="description",
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
