# Generated by Django 4.1.1 on 2022-11-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_jobpost_apply_alter_jobpost_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
