# Generated by Django 4.1.1 on 2022-11-26 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploadapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Uploads",
            new_name="Upload",
        ),
    ]
