# Generated by Django 4.1.1 on 2022-11-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0016_remove_jobpost_apply_delete_apply"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submit_CV", models.FileField(upload_to="")),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("current_company", models.CharField(max_length=200)),
                ("linkedin", models.URLField()),
                ("twitter", models.URLField()),
                ("github", models.URLField()),
                ("portfolio", models.URLField()),
                ("cover_letter", models.CharField(max_length=1000)),
                ("Gender", models.CharField(max_length=20)),
                ("race", models.CharField(max_length=200)),
                ("veteran_status", models.CharField(max_length=200)),
                (
                    "job_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.jobpost",
                    ),
                ),
            ],
        ),
    ]
