# Generated by Django 4.1.1 on 2022-11-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applybank", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apply",
            name="job_id",
        ),
    ]
