# Generated by Django 4.1.1 on 2022-11-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_jobpost_description"),
        ("applybank", "0002_remove_apply_job_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Apply",
            new_name="ApplyForm",
        ),
    ]
