# Generated by Django 4.1.1 on 2022-11-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applybank", "0003_rename_apply_applyform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyform",
            name="Gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=20,
            ),
        ),
    ]
